version: "3"
services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      ENV HOST: 0.0.0.0
      ENV NUXT_HOST: 0.0.0.0
      ENV NUXT_PORT: 3000
    ports:
      - "3000:3000"
